notifications:
  email:
    on_success: never
    on_failure: always
language: python
python:
    - "3.5"

install: "pip install -r requirements.txt"
script: py.test --cov=gendb
# whitelist
branches:
    only:
       - master
after_success:
    - coveralls
